# Host to use for canonical URL generation (without trailing slash)
host: example.docs.tax.service.gov.uk

# Header-related options
show_govuk_logo: true
service_name: Absolute link generation reproduction example
service_link: https://example.docs.tax.service.gov.uk
phase: Beta

# Links to show on right-hand-side of header
header_links:
  About: https://www.larry-the-cat.service.gov.uk/about
  Get Started: https://www.larry-the-cat.service.gov.uk/get-started
  Documentation: /
  Support: https://www.larry-the-cat.service.gov.uk/support

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: false

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: hmrc/example-tech-docs-template-absolute-links
